name: Build Python Package

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-22.04, windows-2019, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23
        env:
          CIBW_SKIP: "cp36-* cp37-* cp38-* pp* *-musllinux_* *_i686 *-win32"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BEFORE_ALL_LINUX: >
            cd "/usr/bin" && 
            curl -fLO https://releases.bazel.build/5.3.2/release/bazel-5.3.2-linux-x86_64 && 
            chmod +x bazel-5.3.2-linux-x86_64 && 
            ln -s bazel-5.3.2-linux-x86_64 bazel
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
