name: Build Python Package

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}, Python ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019]
        py: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup-py
        with:
          python-version: ${{ matrix.py }}

      - name: Build release distributions
        shell: bash  # workaround of https://github.com/tensorflow/tensorflow/issues/56420
        run: |
          export PYTHON_BIN_PATH=$(echo '${{ steps.setup-py.outputs.python-path }}' | sed 's#\\#/#g')
          python -m pip wheel --no-deps --wheel-dir=dist .

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: visqol-${{ matrix.os }}-py${{ matrix.py }}
          path: dist/

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: bazel-bin-${{ matrix.os }}-py${{ matrix.py }}
          path: bazel-bin/
